name: "Pages"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/preview.yaml"
      - "public/**"
      - "src/**"
      - "index.html"
      - "package*.json"

env:
  crawler-id: ""
  purge-domain: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    if: ${{ !contains(github.event.head_commit.message, '#nodeploy') || github.actor != 'dependabot[bot]' }}
    uses: cssnr/workflows/.github/workflows/npm-build.yaml@master
    permissions:
      contents: read
    with:
      build: "npm run build"
      path: "dist"
      pages: true
    secrets:
      webhook: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4

      - name: "Send Deploy Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: |
            GitHub Pages Deployed: ${{ steps.deployment.outputs.page_url }}

  post:
    name: "Post-Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy

    steps:
      - name: "Purge Cache"
        if: ${{ env.purge-domain != '' }}
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          zones: ${{ env.purge-domain }}
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: "Algolia Crawler"
        if: ${{ env.crawler-id != '' }}
        uses: cssnr/algolia-crawler-action@v2
        with:
          crawler_id: ${{ env.crawler-id }}
          crawler_user_id: ${{ secrets.CRAWLER_USER_ID }}
          crawler_api_key: ${{ secrets.CRAWLER_API_KEY }}

      - name: "Send Discord Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: |
            GitHub Pages Deploy Failed: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
